### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [wiscsims/PIBC#1]
Please add a bit more description in metadata.txt of what the plugin does

**Comment by saburo** [comment]
Both "Description" and "About" in metadata.txt and the plugin page on the QGIS plugin repository site are have been updated.  Do I need to remove old one and re-upload new zip file to QGIS plugin repository site?

**Comment by NyakudyaA** [comment]
> Both "Description" and "About" in metadata.txt and the plugin page on the QGIS plugin repository site are have been updated. Do I need to remove old one and re-upload new zip file to QGIS plugin repository site?

Yes, just reupload. It will then update the old plugin. Once I get a notification then you are good to go

**Comment by saburo** [comment]
@NyakudyaA Thanks!
